server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:5432/postgres_db?currentSchema=patientservice
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret}
